/* config.h.  Generated by configure.  */
#define HAVE_STDIO_H 1
#define HAVE_GL_GL_H 1
/* #undef HAVE_GL_GLX_H */
/* #undef HAVE_LIBGL */

#ifndef HAVE_STDIO_H
#error You need stdio.h
#endif

#ifndef HAVE_GL_GL_H
#error You need to install the OpenGL headers
#endif

#ifndef HAVE_GL_GLX_H
#error You need to install the glc headers
#endif

#ifndef HAVE_LIBGL
#error You either dont have libGL or glXGetProcAddress is not exported
#endif


